
[spawning]
	#Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn
	#Range: 0 ~ 1000
	anglerfishSpawnWeight = 2
	#Random roll chance to enable mob spawning. Higher number = lower chance of spawning
	#Range: > 0
	anglerfishSpawnRolls = 1
	#Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn
	#Range: 0 ~ 1000
	bluefinfishSpawnWeight = 4
	#Random roll chance to enable mob spawning. Higher number = lower chance of spawning
	#Range: > 0
	bluefinfishSpawnRolls = 2

[dangerZone]
	#How many cpu cores some mobs(elephants, leafcutter ants, bison etc) should utilize when pathing. Bigger number = less impact on TPS
	#Range: 1 ~ 100
	pathfindingThreads = 5

